// Generated by CoffeeScript 1.3.3

define(function(require) {
  return {
    getFlickApiUrl: function(options) {
      var key, quantity;
      key = options.key, quantity = options.quantity;
      return "http://api.flickr.com/services/rest/?method=flickr.photos.search&api_key=a47e50dcce48c46c58f9b8c622c42a18&sort=relevance&text=" + key + "&per_page=" + quantity + "&format=json&jsoncallback=?";
    },
    getImageUrl: function(farm, server, id, secret, format) {
      if (format == null) {
        format = q;
      }
      return "http://farm" + farm + ".staticflickr.com/" + server + "/" + id + "_" + secret + "_" + format + ".jpg";
    },
    getImages: function(keyword, callback, format) {
      var _callback,
        _this = this;
      if (keyword == null) {
        keyword = "moon";
      }
      if (format == null) {
        format = "q";
      }
      /* returns an array of image urls
      */

      _callback = function(rawdata, status) {
        var data, photo;
        data = (function() {
          var _i, _len, _ref, _results;
          _ref = rawdata.photos.photo;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            photo = _ref[_i];
            _results.push(this.getImageUrl(photo.farm, photo.server, photo.id, photo.secret, format));
          }
          return _results;
        }).call(_this);
        return callback.apply(null, [data, status, rawdata]);
      };
      return jQuery.get(this.getFlickApiUrl({
        keyword: keyword,
        quantity: 20
      }), _callback, "jsonp");
    },
    search: function() {
      return this.getImages.apply(this, arguments);
    }
  };
});
