// Generated by CoffeeScript 1.3.3

define(function(require) {
  return {
    Node: require("./Node"),
    twodee: require("./twodee/twodee"),
    threedee: {
      Node3d: require("./threedee/Node3d")
    }
  };
});
