// Generated by CoffeeScript 1.3.3
/* coordinates.events.CoordinateNodeEvent
*/

var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function(require) {
  var CoordinateNodeEvent, Event;
  Event = require("./helpers/Event");
  return CoordinateNodeEvent = (function(_super) {

    __extends(CoordinateNodeEvent, _super);

    CoordinateNodeEvent.prototype.ADD = "coordyNodeAdd";

    CoordinateNodeEvent.prototype.REMOVE = "coordyNodeRemove";

    function CoordinateNodeEvent(type, node, bubbles, cancelable) {
      this.node = node;
      if (bubbles == null) {
        bubbles = false;
      }
      if (cancelable == null) {
        cancelable = false;
      }
      CoordinateNodeEvent.__super__.constructor.call(this, type, bubbles, cancelable);
    }

    CoordinateNodeEvent.prototype.clone = function() {
      return new CoordinateNodeEvent(this.type, this.node, this.bubbles, this.cancelable);
    };

    return CoordinateNodeEvent;

  })(Event);
});
