// Generated by CoffeeScript 1.3.3
/* coordinates.events
*/

define(function(require) {
  var CoordinateNodeEvent, helpers;
  helpers = require("./helpers/helpers");
  CoordinateNodeEvent = require("./CoordinatesNodeEvent");
  return {
    helpers: helpers,
    CoordinateNodeEvent: CoordinateNodeEvent
  };
});
