// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function(require) {
  var ImageView;
  require("vendor/jquery.min");
  require("vendor/backbone-min");
  return ImageView = (function(_super) {

    __extends(ImageView, _super);

    function ImageView() {
      return ImageView.__super__.constructor.apply(this, arguments);
    }

    /* affiche les images issues du service utilisé
    */


    ImageView.prototype.attributes = {
      "data-type": "thumbnail"
    };

    ImageView.prototype.events = {
      "load": "imageLoaded",
      "mouseover": "mouseover",
      "mouseout": "mouseout"
    };

    ImageView.prototype.initialize = function(params) {
      return this.model.on("change", this.render, this);
    };

    ImageView.prototype.imageLoaded = function(event) {
      return this.$el.css({
        opacity: 1
      });
    };

    ImageView.prototype.mouseover = function() {
      this.$el.css({
        width: "60px",
        height: "60px"
      });
    };

    ImageView.prototype.mouseout = function() {
      this.$el.css({
        width: "50px",
        height: "50px"
      });
    };

    ImageView.prototype.load = function(src) {
      this.$el.attr("src", null);
      this.$el.css({
        opacity: 0.2
      });
      return this.$el.attr("src", src);
    };

    ImageView.prototype.render = function() {
      return this.$el.attr('src', this.model.get("url"));
    };

    return ImageView;

  })(Backbone.View);
});
