// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function(require) {
  var Node, Node2d;
  Node = require("../Node");
  return Node2d = (function(_super) {

    __extends(Node2d, _super);

    function Node2d(link, x, y, jitterX, jitterY) {
      var rotation;
      if (link == null) {
        link = null;
      }
      if (x == null) {
        x = 0;
      }
      if (y == null) {
        y = 0;
      }
      if (jitterX == null) {
        jitterX = 0;
      }
      if (jitterY == null) {
        jitterY = 0;
      }
      Node2d.__super__.constructor.call(this, link);
      rotation = 0;
      this.getX = function() {
        return x;
      };
      this.setX = function(value) {
        return x = value;
      };
      this.getY = function() {
        return y;
      };
      this.setY = function(value) {
        return y = value;
      };
      this.getJitterX = function() {
        return jitterX;
      };
      this.setJitterX = function(value) {
        return jitterX = Math.random() * value * (((Math.random() > 0.5) != null) - {
          1: 1
        });
      };
      this.getJitterY = function() {
        return jitterY;
      };
      this.setJitterY = function(value) {
        return jitterY = Math.random() * value * (((Math.random() > 0.5) != null) - {
          1: 1
        });
      };
      this.getRotation = function() {
        return rotation;
      };
      this.setRotation = function(value) {
        return rotation = value;
      };
      this.setJitterX(jitterX);
      this.setJitterY(jitterY);
    }

    Node2d.prototype.clone = function() {
      var n;
      n = new Node2d(this.getLink(), this.getX(), this.getY(), this.getJitterX(), this.getJitterY);
      n.setRotation(this.getRotation());
      return n;
    };

    Node2d.prototype.toObject = function() {
      return {
        x: this.getX(),
        y: this.getY(),
        jitterX: this.getJitterX(),
        jitterY: this.getJitterY(),
        rotation: this.getRotation()
      };
    };

    Node2d.prototype.toString = function() {
      return "[object Node2d]";
    };

    return Node2d;

  })(Node);
});
