// Generated by CoffeeScript 1.3.3

define(function(require) {
  /* MenuTemplate
  */
  return "<% for( i in layouts ){%>\n    <li data-type=\"<%-layouts[i].type %>\" > \n        <a href='#layout2d/<%- layouts[i].type %>'> <%- layouts[i].name  || layouts[i].type %> </a>\n    </li>\n<%}%>";
});
