// Generated by CoffeeScript 1.3.3
/* coordinates.events.helpers
*/

define(function(require) {
  var Event, EventDispatcher, EventPhase, IEventDispatcher;
  Event = require("./Event");
  EventDispatcher = require("./EventDispatcher");
  EventPhase = require("./EventPhase");
  IEventDispatcher = require("./IEventDispatcher");
  return {
    Event: Event,
    EventDispatcher: EventDispatcher,
    EventPhase: EventPhase,
    IEventDispatcher: IEventDispatcher
  };
});
