// Generated by CoffeeScript 1.3.3

define(function(require) {
  var IEventDispatcher;
  return IEventDispatcher = (function() {

    function IEventDispatcher() {}

    IEventDispatcher.prototype.addEventListener = function(type, listener) {};

    IEventDispatcher.prototype.dispatchEvent = function(event) {};

    IEventDispatcher.prototype.hasEventListener = function(type) {};

    IEventDispatcher.prototype.removeEventLisnter = function(type, listener) {};

    IEventDispatcher.prototype.willTrigger = function(type) {};

    return IEventDispatcher;

  })();
});
