// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function(require) {
  var AppConfig, Coordinates;
  require("vendor/backbone-min");
  Coordinates = require("coordinates/coordinates");
  return AppConfig = (function(_super) {

    __extends(AppConfig, _super);

    function AppConfig() {
      return AppConfig.__super__.constructor.apply(this, arguments);
    }

    return AppConfig;

  })(Backbone.Model);
});
