// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function(require) {
  var ImageModel;
  return ImageModel = (function(_super) {

    __extends(ImageModel, _super);

    function ImageModel() {
      return ImageModel.__super__.constructor.apply(this, arguments);
    }

    /* contient les données d'un ImageVIew
    */


    ImageModel.prototype.defaults = {
      src: "img/spinner.gif"
    };

    return ImageModel;

  })(Backbone.Model);
});
