// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function(require) {
  var LayoutModel;
  return LayoutModel = (function(_super) {

    __extends(LayoutModel, _super);

    function LayoutModel() {
      return LayoutModel.__super__.constructor.apply(this, arguments);
    }

    LayoutModel.prototype.defaults = {
      type: 'Flow',
      options: {
        width: 500,
        height: 500
      }
    };

    return LayoutModel;

  })(Backbone.Model);
});
