// Generated by CoffeeScript 1.3.3
/* coordinates.links.Link
*/

define(function(require) {
  var Link;
  return Link = (function() {

    function Link(x, y, rotation) {
      if (x == null) {
        x = 0;
      }
      if (y == null) {
        y = 0;
      }
      if (rotation == null) {
        rotation = 0;
      }
      this.getX = function() {
        return x;
      };
      this.setX = function(value) {
        return x = value;
      };
      this.getY = function() {
        return y;
      };
      this.setY = function(value) {
        return y = value;
      };
      this.getRotation = function() {
        return rotation;
      };
      this.setRotatation = function(value) {
        return rotation = value;
      };
    }

    Link.prototype.toString = function() {
      return "[object Link]";
    };

    return Link;

  })();
});
