// Generated by CoffeeScript 1.3.3
/* coordinates.links.Link
*/

define(function(require) {
  var Link;
  return Link = (function() {

    function Link(element, x, y, rotation) {
      if (x == null) {
        x = 0;
      }
      if (y == null) {
        y = 0;
      }
      if (rotation == null) {
        rotation = 0;
      }
      Object.defineProperties(this, {
        x: {
          get: function() {
            return x;
          },
          set: function(v) {
            return x = v;
          }
        },
        y: {
          get: function() {
            return y;
          },
          set: function(v) {
            return y = v;
          }
        },
        rotation: {
          get: function() {
            return rotation;
          },
          set: function(v) {
            return rotation = v;
          }
        },
        element: {
          get: function() {
            return element;
          },
          set: function(v) {
            return element = v;
          }
        }
      });
    }

    Link.prototype.toString = function() {
      return "[object Link]";
    };

    return Link;

  })();
});
