// Generated by CoffeeScript 1.3.3

define(function(require) {
  return {
    Link: require("./Link"),
    threedee: {
      Link3d: require("./threedee/Link3d")
    },
    DOMLink2d: require("./DOMLink2d")
  };
});
